### PR TITLE
Divided graduation registration into semester and year.

### PR DESCRIPTION
**Pull request by KellenJames**
-Added two dropdowns in the registration site, one for year and one for semester of expected graduation, which dynamically changes each year.
-Altered the lambda code for registering new users to accept a grad_semester and grad_year, and removed the grad_date
-Site was tested in aws, and the lambda code was also tested and the contents showed up in the DynamoDB table

### CODE REVIEW

**Comment by ophilli** [comment]
Can you rebase this & update the build so that we can merge it?

**Comment by ophilli** [comment]
Also, when you rebase please remove useless commits like the merge commits and the commits related to PITR & the ones that reverted the PITR changes.

[89a53f6](https://github.com/clemsonMakerspace/unified-makerspace/pull/64/commits/89a53f6ef7bd96404cabf82cd6c50ba764a81f67)
[22fb58e](https://github.com/clemsonMakerspace/unified-makerspace/pull/64/commits/22fb58e3f4275a582f352b56f6cf206ac36e79bd)
[236a1b6](https://github.com/clemsonMakerspace/unified-makerspace/pull/64/commits/236a1b698a04b896f30fbda216ae42372139eb0a)
[9a9ffe6](https://github.com/clemsonMakerspace/unified-makerspace/pull/64/commits/9a9ffe681abc51303dd1219a63697c2bcb4712c9)
[88e4dcc](https://github.com/clemsonMakerspace/unified-makerspace/pull/64/commits/88e4dccb85ab65b342dd7b5b6cf90e7064fde61e)
[08975f2](https://github.com/clemsonMakerspace/unified-makerspace/pull/64/commits/08975f28e809487ad072f7eff924584b7008f031)

**Comment by KellenJames** [comment]
I rebased the branch and updated the changes so that they should now work with the changes Josh had made.

**Comment by ophilli** [comment]
Are the site build artifacts up to date in this PR?

**Comment by KellenJames** [comment]
I went ahead and pulled and built the site again just to be sure, so it should be up to date.

**Comment by ophilli** [comment]
Discussed this PR in our 2022-04-01 meeting. @KellenJames can you please resolve the conflicts in this PR & update the front-end build as needed?

**Pull request closed without merging**
