### PR TITLE
Try Building the Visitor Frontend in the CodePipeline

### PR DESCRIPTION
**Pull request by Mjtlittle**
## Changes
- Try building the visitor frontend in the codepipeline before deploying the cdk
  - not sure if this will work as intended, this change is to test on the actual pipeline, and can be reverted if the CI stage fails
  - eventually move the build artifact of this step into the `cdk/visit/console` folder for actual deployment

### CODE REVIEW

**Review by dggorsen — APPROVED** [review]
This all looks reasonable to me! Really nice work sorting through the ambiguity here. Let me talk with Owen about merging tomorrow.

**Comment by ophilli** [comment]
I squashed & merged the 3 commits from #79 and now GitHub doesn't know how to resolve the conflicts. Can you rebase or cherry-pick f023e45251e23b9533f27bab88fa24725c2bf3d2 onto mainline & then force push?

When you split the "Testing pipeline build of frontend" commit into its own PR from #79 you included the 3 commits from #79 here - I think it would have been better to put f023e45251e23b9533f27bab88fa24725c2bf3d2 onto its own branch & set the upstream as the branch #79 was on. This would have made this PR diff only show f023e45251e23b9533f27bab88fa24725c2bf3d2 and I suspect it would have made rebasing easier after I squashed the commits.

**Review by ophilli — CHANGES_REQUESTED** [review]
squashed & merged the 3 commits from https://github.com/clemsonMakerspace/unified-makerspace/pull/79 and now GitHub doesn't know how to resolve the conflicts. Can you rebase or cherry-pick https://github.com/clemsonMakerspace/unified-makerspace/commit/f023e45251e23b9533f27bab88fa24725c2bf3d2 onto mainline & then force push back to this branch?

When you split the "Testing pipeline build of frontend" commit into its own PR from https://github.com/clemsonMakerspace/unified-makerspace/pull/79 you included the 3 commits from https://github.com/clemsonMakerspace/unified-makerspace/pull/79 here - I think it would have been better to put https://github.com/clemsonMakerspace/unified-makerspace/commit/f023e45251e23b9533f27bab88fa24725c2bf3d2 onto its own branch & set the upstream as the branch https://github.com/clemsonMakerspace/unified-makerspace/pull/79 was on. This would have made this PR diff only show https://github.com/clemsonMakerspace/unified-makerspace/commit/f023e45251e23b9533f27bab88fa24725c2bf3d2 and I suspect it would have made rebasing easier after I squashed the commits.

**Comment by ophilli** [comment]
I reverted https://github.com/clemsonMakerspace/unified-makerspace/commit/4e9c21224a2a5df242c5830ff0e46241a62e820e with 7df212251feac6b412e41895b6159756b2061229 because during testing of this change after deployment to prod I noticed that it was posting all requests to https://www.google.com/ instead of https://api.cumaker.space/.

**Comment by ophilli** [comment]
I've just tested https://visit.cuMaker.space/ after deployment of https://github.com/clemsonMakerspace/unified-makerspace/commit/7df212251feac6b412e41895b6159756b2061229 and the rollback work. https://github.com/clemsonMakerspace/unified-makerspace/commit/4e9c21224a2a5df242c5830ff0e46241a62e820e is confirmed bad.

**Comment by Mjtlittle** [comment]
> I've just tested https://visit.cuMaker.space/ after deployment of [7df2122](https://github.com/clemsonMakerspace/unified-makerspace/commit/7df212251feac6b412e41895b6159756b2061229) and the rollback work. [4e9c212](https://github.com/clemsonMakerspace/unified-makerspace/commit/4e9c21224a2a5df242c5830ff0e46241a62e820e) is confirmed bad.

Oh dang, sorry I left that there. I was testing the change and deployed to my test env, and forgot to rebuild the app for the actual pr.

**Comment by Mjtlittle** [comment]
> squashed & merged the 3 commits from #79 and now GitHub doesn't know how to resolve the conflicts. Can you rebase or cherry-pick [f023e45](https://github.com/clemsonMakerspace/unified-makerspace/commit/f023e45251e23b9533f27bab88fa24725c2bf3d2) onto mainline & then force push back to this branch?
> 
> When you split the "Testing pipeline build of frontend" commit into its own PR from #79 you included the 3 commits from #79 here - I think it would have been better to put [f023e45](https://github.com/clemsonMakerspace/unified-makerspace/commit/f023e45251e23b9533f27bab88fa24725c2bf3d2) onto its own branch & set the upstream as the branch #79 was on. This would have made this PR diff only show [f023e45](https://github.com/clemsonMakerspace/unified-makerspace/commit/f023e45251e23b9533f27bab88fa24725c2bf3d2) and I suspect it would have made rebasing easier after I squashed the commits.

I just rebased the branch onto the mainline changes. 

This pr is from last week however; I think you mentioned not wanting to merge a change like this into prod, so I planned on standing up my own pipeline to test this, and potentially solve the environment dependent build aspect of it aswell. This could remove the need to build the site in the mean time, it just wont have the correct api endpoints.

*ill rebase it on #85 / #79 once its merged and flattened

**Comment by Mjtlittle** [comment]
Ive done some more testing on my end, ill open a new PR with updated changes on a new branch.

*Ill link it on here when I open it.

**Pull request closed without merging**
