### PR TITLE
Fixed; Replaced CRA with Vite and Exposed Build Env Variable for API

### PR DESCRIPTION
**Pull request by Mjtlittle**
**SAME PR AS #79, BUT FIXED THE FRONTEND BUILD**

## Changes

- Replaced Create-React-App with Vite
    - speeds up dev load time drastically
    - dependancies are cleaner and easier to audit in package.json
    - ability to speed things up further in the future with plugins
    - may want to change eslint config in the future
- Added environment variable api to build
    - setting `VITE_API_ENDPOINT` on build controls what api the frontend will use
- Testing building the frontend within the code pipeline
    - this does not do anything yet, its just to see if the build is successful and we can see its artifacts in the bucket
    - this shouldn't cause any problem on prod, at most it will fail the pipeline and we can fix it

## Deployment

[https://d1kquov5x5h6vg.cloudfront.net/](https://d1kquov5x5h6vg.cloudfront.net/)

### CODE REVIEW

**Comment by Mjtlittle** [comment]
Sorry @ophilli, I realized I didnt have a PR open for the changes you reverted this morning. I had assumed you just reverted the build; this should be fixed though. I deployed it to my dev environment and its hitting the correct api now (https://d1kquov5x5h6vg.cloudfront.net/).

*[`ed00930`](https://github.com/clemsonMakerspace/unified-makerspace/pull/85/commits/ed009301d60c405fc18616a27ede26db4adeb9cd) has the change

**Review by dggorsen — APPROVED** [review]
LG2M! Please check with me tomorrow and I will carve out some time to get this merged and track it through the pipeline. Just want to make sure you are ready for this to be merged (and that nothing here conflicts with the other PR that I just commented on)

**Comment by ophilli** [comment]
Build artifacts should be up to date & ready to go.

Waiting on scheduling from @Mjtlittle for time to verify deployment. Once you let us know when you can verify I'm happy to merge it.

**Comment by Mjtlittle** [comment]
Tested this by visiting the site and making both a sign-in and register request (with username 'DELETE ME'). The dynamo table reflected both requests. Also if you make a request and look at the assets it pulls from the cdn, they are the Vite assets and not the CRA ones (different build artifact naming scheme).

**Pull request merged**
