### PR TITLE
Added a 404 Page for Visitor Front End

### PR DESCRIPTION
**Pull request by mikebrandin**
This PR adds a 404 page that tells the user their is an error with the URL requested and provides a link to be redirected to the home page. It adds the `NotFoundPage` folder with a `NotFoundPage.tsx` file within. This PR resolves Issue #19 .

### CODE REVIEW

**Comment by mikebrandin1** [comment]
This PR resolves Issue #19

**Comment by ophilli** [comment]
Can you update this PR & include info about how you tested it? Presumably you uploaded it to your dev stack - it would be nice to include screenshots or links that let approvers see how this looks.

**Comment by dggorsen** [comment]
> Can you update this PR & include info about how you tested it? Presumably you uploaded it to your dev stack - it would be nice to include screenshots or links that let approvers see how this looks.

I think this is a great idea. Typically how we do FE development is by pasting a link to our local stack (might be a CloudFront distribution for you) so that we can see the changes in action

**Comment by ophilli** [comment]
@mikebrandin1 you should probably make your `pull` commands `rebase` instead of `merge`.

You can do this with `git pull --rebase` or `git config --global pull.rebase true`. More info [here](https://spin.atomicobject.com/2020/05/05/git-configurations-default/).

**Pull request merged**
