### PR TITLE
Add lambda test, api test, fixed testing

### PR DESCRIPTION
**Pull request by lrboyer**
Added new lambda test for new /quiz api to test_quiz
- test post
- test get

Added new api_gateway test to test_api
- test post
- test get

Fixed pytest api testing
- pytest wasn't collecting the test cases properly in file test_api so I refactored so there is no more init() in the class.

Added onto testing_script
- testing_script is used by AWS codepipeline for testing so copied over new test from test_api

Fixed warning in log_visit
- recommended to use self.logger.warning instead of self.logger.warn

Which is better: use raise Exception or assert?

Merge after https://github.com/clemsonMakerspace/unified-makerspace/pull/142

### CODE REVIEW

**Comment by lrboyer** [comment]
I have tested these test cases locally with pytest and the testing_script using my dev account (the new quiz api and lambda functionality) and they all pass.

**Comment by lrboyer** [comment]
Also would it make sense for api_test and the testing_script to be the mostly the same? The only extra thing testing_script would need would a handler function that will run all of the test and print the response. They basically have the same code except one uses pytest. 
But I'm guessing in the future we would want aws pipeline to run pytest and not our testing_script

**Review by Mjtlittle — APPROVED** [review]
Asserts raise an exception if they fail, so here they are functionally the same (assert maybe makes more sense in a testing context semantically)

**Comment by Mjtlittle** [comment]
It looks like the new tests here are failing because its failing to find the environment variable `QUIZ_LIST_TABLE_NAME`. In other tests ([here](https://github.com/clemsonMakerspace/unified-makerspace/blob/mainline/cdk/visit/lambda_code/log_visit/log_visit.py#L24)) it looks like we are checking to see if None is passed and not looking to the environment for this value when that is the case.

**Comment by lrboyer** [comment]
> It looks like the new tests here are failing because its failing to find the environment variable `QUIZ_LIST_TABLE_NAME`. In other tests ([here](https://github.com/clemsonMakerspace/unified-makerspace/blob/mainline/cdk/visit/lambda_code/log_visit/log_visit.py#L24)) it looks like we are checking to see if None is passed and not looking to the environment for this value when that is the case.



> It looks like the new tests here are failing because its failing to find the environment variable `QUIZ_LIST_TABLE_NAME`. In other tests ([here](https://github.com/clemsonMakerspace/unified-makerspace/blob/mainline/cdk/visit/lambda_code/log_visit/log_visit.py#L24)) it looks like we are checking to see if None is passed and not looking to the environment for this value when that is the case.

I forgot to add these the new env variables here: https://github.com/clemsonMakerspace/unified-makerspace/blob/5422cedfa5b2b79f242c3e8d91c24101178c4fb5/.github/workflows/pytest.yml#L29

**Pull request merged**
